---
- hosts: localhost
  gather_facts: False

  vars:
    region: us-east-2
    instance_type: t2.micro
    ami: ami-0b500ef59d8335eee
    keypair: ubuntu 

  tasks:
    - name: Create new EC2 Instance
      ec2:
        key_name: "{{ keypair }}"
        aws_access_key: "{{ aws_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        group: launch-wizard-13 #security group name
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        wait: true
        region: "{{ region }}"
        count: 1
        count_tag:
          Name: "Demo"
        instance_tags:
          Name: "Demo"
        vpc_subnet_id: "subnet-a015cbec"
        assign_public_ip: yes
      register: ec2

    - name: print ec2 module output
      debug: var=ec2

    - debug:
        msg: "{{ item['private_ip'] }}"
      with_items: "{{ ec2.instances }}"

    - name: wait for ssh port
      wait_for: port-22 host-"{{ item['private_ip'] }}" timeout-120 state-started
      with_items: "{{ ec2.instances }}"

    - name: Create a new inventory
      add_host:
        host_name: "{{ item['private ip'] }}"
        ansible_user: ec2-user
        ansible_ssh_key: /root/.ssh/ansibleclientpractice1.pem
        with_items: "{{ ec2.instances }}"

    - set_fact: ip_list= "[]"

    - name: Construct IP List
      set_fact: ip_list= "{{ ip_list }} + ['{{ item.private_ip }}']"
      with_items: "{{ ec2.instances }}"

    - name: Print IP List
      debug: msg="{{ ip_list }}"
 
