---
- hosts: localhost
 
  vars:
    array_of_numbers:
      - 11
      - 12
      - 13
      - 14
  tasks:
    - name: print the minimum of array
      debug: msg='lowest= {{ array_of_numbers |min }}'
